server:
  port: 8084
spring:
  application:
    name: indexing-service
  kafka:
    bootstrap-servers: localhost:9092,3.37.147.123:9092,3.36.188.73:9092,54.180.180.120:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: indexing-group2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
