apiVersion: v1
kind: ConfigMap
metadata:
  name: indexing-service-config
  namespace: indexing
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_SERVER_PORT: "8084"
  EUREKA_URL: http://eureka-service.default.svc.cluster.local:8761/eureka
  KAFKA_SCHEMA_REGISTRY_SERVER: 43.201.43.88:8081

