{
  "type": "record",
  "name": "ClickEventLog",
  "namespace": "com.goormplay.indexingservice.avro",
  "fields": [
    { "name": "userId", "type": "string" },
    { "name": "videoId", "type": "string" },
    {
      "name": "timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    { "name": "eventType", "type": "string" },
    {
      "name": "contentCategory",
      "type": {
        "type": "array",
        "items": "string"
      }
    },
    { "name": "page", "type": "string" }
  ]
}